export const DbTables = {
  UsersAdm: 'users-adm',
  Company:'company',
  Terms: 'terms',
  New: 'news',
  Category: 'category',
  Cards: 'cards',
  Requests: 'request',
  Vistas: 'vistas',
  Notas: 'notas',
  Customers: 'customers-adm',
  Answer:'answer',
  Wall:'wall',
  Frequent:'frequent-questions',
  Users: 'users',
  Country: 'country',
  Equipment: 'equipment',
  Warehouse: 'warehouse',
  Position: 'position',
  Holder: 'record',
  Message: 'message',
  Audit: 'audit',
  Version: 'version'
};
