export class RequestDto {
    arraySearch?: any = [];
    id:string;
    TotalCubicMeters: number;
    TotalExtraHelp: number;
    anotherDistance: number;
    bodegaNumber: string; 
    cubicMeters: number;
    currentAddress: string; 
    currentFDepto: string; 
    currentFOffice: string; 
    currentHome: string; 
    currentNDepto   : string; 
    currentNOffice: string; 
    date: string; 
    dateCreated: string; 
    dateIonic: string; 
    dateTime: string; 
    destinationAddress: string; 
    destinationFDepto: string; 
    destinationFOffice: string; 
    destinationHome: string; 
    destinationNDepto: string; 
    destinationNOffice: string; 
    distance: number;
    elevatorAvailableCDepto: string;
    elevatorAvailableCOffice: string;
    elevatorAvailableDDepto: string;
    elevatorAvailableDOffice: string;
    elevatorNoSpace: string;
    elevatorNoSpace2: string;
    elevatorSpaceCDepto: string;
    elevatorSpaceCOffice: string;
    elevatorSpaceDDepto: string;
    elevatorSpaceDOffice: string;
    email: string;
    hotelPerDiem: number;
    hour: string;
    isChecked: boolean;
    items: any[];
    lat: number;
    latDestination: number;
    lng: number;
    lngDestination: number;
    locality: string;
    localityDestination: string;
    name: string;
    parking: boolean;
    parkingDestination: boolean;
    phoneNumber: number;
    priceExtraHelp: number;
    pricePacking: number;
    priceTotalKm: number;
    priceUnPackingt: number;
    region: string;
    regionDestination: string;
    status: string;
    total: number;
    totalNoParking: number;
    transportConductor: string;
    totalNoParkingDestination: number;
    totalPay: number;
    userExtraHelp: boolean;
    userPacking: boolean;
    userUnPackingt: boolean;

}
